name: linters

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

concurrency: ci-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: StandardRB Check
        run: bundle exec standardrb

      - name: StandardJS Check
        run: yarn standard
